namespace XAlarm.Center.Domain.Shared;

public enum Constants
{
    CredentialId = 1,
    CredentialSecret = 2,
    MaxUsers = 3,
    Audience = 4,
    ValidIssuer = 5,
    MetadataUrl = 6,
    BaseUrl = 7,
    AdminCliUrl = 8,
    GroupsUrl = 9,
    GetUserUrl = 10,
    GetUsersUrl = 11,
    UpdateUserUrl = 12,
    DeleteUserUrl = 13,
    GroupMembersUrl = 14,
    ExecuteActionsEmailUrl = 15,
    AdminUrl = 16,
    TokenUrl = 17,
    AdminCliClientId = 18,
    AdminCliClientSecret = 19,
    AdminCliGrantType = 20,
    AdminClientId = 21,
    AdminClientSecret = 22,
    AuthClientId = 23,
    AuthClientSecret = 24,
    AuthScope = 25,
    AuthGrantType = 26,
    AuthSubjectTokenType = 27,
    AuthSubjectIssuer = 28,
    TokenGoogleClientId = 29,
    TokenGoogleClientSecret = 30,
    TokenGoogleScope = 31,
    TokenGoogleGrantType = 32,
    TokenGoogleSubjectTokenType = 33,
    TokenGoogleSubjectIssuer = 34
}