// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XAlarm.Center.Infrastructure;

#nullable disable

namespace XAlarm.Center.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250314150541_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("XAlarm.Center.Domain.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("DongleId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("dongle_id");

                    b.Property<string>("InvoiceNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("invoice_no");

                    b.Property<Guid>("ProjectGroupId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_group_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("project_name");

                    b.Property<string>("ProjectOptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("project_options");

                    b.Property<DateTime>("ValidUntil")
                        .HasColumnType("TEXT")
                        .HasColumnName("valid_until");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_project_id");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("XAlarm.Center.Domain.Settings.GlobalSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("EmailOptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("email_options");

                    b.Property<string>("LineOptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("line_options");

                    b.Property<string>("SmsOptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("sms_options");

                    b.Property<string>("TelegramOptions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("telegram_options");

                    b.HasKey("Id")
                        .HasName("pk_global_settings");

                    b.ToTable("global_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
