// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XAlarm.Center.Infrastructure;

#nullable disable

namespace XAlarm.Center.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250307154301_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("XAlarm.Center.Domain.Settings.GlobalSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("GeneralSetting")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("general_setting");

                    b.HasKey("Id")
                        .HasName("pk_global_settings");

                    b.ToTable("global_settings", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
